### ISSUE TITLE
On game over in snakegame.html, page should not redirect until one of the game over modal buttons are clicked

### ISSUE THREAD

**Issue by YashasG98** [YashasG98/Multiplayer-Game-Server#18]

**Comment by luciano-7** [comment]
Greetings, I would like to contribute to this project. Can you please assign this to me?

**Comment by zuzaman** [comment]
Hi YashasG98! 

I am a newcomer to Git issues and after finding your project online I looked at this issue and am not sure how to reproduce it. When getting to the game over, I could see two possibilities: 

- Closed the interaction window, in which case when clicking the "Roll" button, the same window is displayed again, but I do not notice any redirections during this

- Clicked on one of the modal buttons, which redirect to the index page

Am I wrong to think that this redirect does not happen anymore?

**Comment by YashasG98** [comment]
The issue was that if you click outside the modal in the case below, there is no option for redirection from that page. We need a solution to ensure that the modal is not made invisible by clicking outside the modal or a feature such that anywhere you click redirects you, with the appropriate UI.

![image](https://user-images.githubusercontent.com/36782406/76184039-6901ea80-61f0-11ea-8a80-a43a0ab228fa.png)

**Comment by zuzaman** [comment]
Ahh okay I understand what you mean now. I did not get this idea based on the original description. I believe I ended up opening a duplicate for this issue after experiencing this. 

Will look into this then.
