### ISSUE TITLE
Add waiting messages on snakegame.html and connect4.html to indicate other player's turn

### ISSUE THREAD

**Issue by YashasG98** [YashasG98/Multiplayer-Game-Server#23]

**Comment by sar99** [comment]
Hey! Can I take up this issue?

**Comment by YashasG98** [comment]
Definitely, please comment here if it is unclear on what is to be done :)

**Comment by kimcarey** [comment]
Hello, this is my first open source project and I'd like to take this one on!

**Comment by YashasG98** [comment]
Hey, sure! Do ask if you have any questions.

**Comment by Shashwatha-Mitra** [comment]
Resolved by commit 651a111
