### ISSUE TITLE
Add a 'Please login first' error message to login page if user tries to enter using other pages

### ISSUE THREAD

**Issue by YashasG98** [YashasG98/Multiplayer-Game-Server#3]

**Comment by will-commited** [comment]
Hi I am looking for a project to contribute to as part of a college assignment, just wondering could I try and take this on.

**Comment by YashasG98** [comment]
@will-commited sure, go ahead. Just ensure you communicate with @Shashwatha-Mitra and me whenever you have any queries or even if you want to add a new feature.

**Comment by julienpan** [comment]
Hi, is this issue still open ? i'd like to try if @will-commited has not finished yet.

**Comment by YashasG98** [comment]
@DelaMarc has completed this too in #33, will close this issue as soon as that is merged

**Comment by YashasG98** [comment]
#33 merged.
