### ISSUE TITLE
Make a proper logout function

### ISSUE THREAD

**Issue by DelaMarc** [YashasG98/Multiplayer-Game-Server#31]
Right now, logging out simply redirects to the home page, without even deleting the user cookies, thus making the logout button unefficient.
I suggest creating a proper logout function that would clear the cookies and redirect to the homepage.

**Comment by julienpan** [comment]
Hello, i'd like to work on this, is this still open ?

**Comment by YashasG98** [comment]
Hey @julienpan, thanks for your interest. @DelaMarc has already taken this up and finished it successfully. I'm waiting for some minor changes to merge it. Please feel free to look at other issues or suggest your own :)

**Comment by YashasG98** [comment]
Solved in #33. Closing.
